language: node_js
node_js:
  - "10.8.0"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set sin the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master