language: node_js
deploy:
  provider: pages
  skip_cleanup: true
  github_token: gh_token  # Set sin the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master